//
//  TDJavaScriptParser.h
//  TDParseKit
//
//  Created by Todd Ditchendorf on 3/17/09.
//  Copyright 2009 Todd Ditchendorf. All rights reserved.
//

#import <ParseKit/ParseKit.h>

@interface TDJavaScriptParser : TDRepetition {
    TDCollectionParser *assignmentOpParser;
    TDCollectionParser *relationalOpParser;
    TDCollectionParser *equalityOpParser;
    TDCollectionParser *shiftOpParser;
    TDCollectionParser *incrementOpParser;
    TDCollectionParser *unaryOpParser;
    TDCollectionParser *multiplicativeOpParser;
    
    TDCollectionParser *programParser;
    TDCollectionParser *elementParser;
    TDCollectionParser *funcParser;
    TDCollectionParser *paramListOptParser;
    TDCollectionParser *paramListParser;
    TDCollectionParser *commaIdentifierParser;
    TDCollectionParser *compoundStmtParser;
    TDCollectionParser *stmtsParser;
    TDCollectionParser *stmtParser;
    TDCollectionParser *ifStmtParser;
    TDCollectionParser *ifElseStmtParser;
    TDCollectionParser *whileStmtParser;
    TDCollectionParser *forParenStmtParser;
    TDCollectionParser *forBeginStmtParser;
    TDCollectionParser *forInStmtParser;
    TDCollectionParser *breakStmtParser;
    TDCollectionParser *continueStmtParser;
    TDCollectionParser *withStmtParser;
    TDCollectionParser *returnStmtParser;
    TDCollectionParser *variablesOrExprStmtParser;
    TDCollectionParser *conditionParser;
    TDCollectionParser *forParenParser;
    TDCollectionParser *forBeginParser;
    TDCollectionParser *variablesOrExprParser;
    TDCollectionParser *varVariablesParser;
    TDCollectionParser *variablesParser;
    TDCollectionParser *commaVariableParser;
    TDCollectionParser *variableParser;
    TDCollectionParser *assignmentParser;
    TDCollectionParser *exprOptParser;
    TDCollectionParser *exprParser;
    TDCollectionParser *commaAssignmentExprParser;
    TDCollectionParser *assignmentExprParser;
    TDCollectionParser *assignmentOpConditionalExprParser;
    TDCollectionParser *conditionalExprParser;
    TDCollectionParser *ternaryExprParser;
    TDCollectionParser *orExprParser;
    TDCollectionParser *orAndExprParser;
    TDCollectionParser *andExprParser;
    TDCollectionParser *andBitwiseOrExprParser;
    TDCollectionParser *bitwiseOrExprParser;
    TDCollectionParser *pipeBitwiseXorExprParser;
    TDCollectionParser *bitwiseXorExprParser;
    TDCollectionParser *caretBitwiseAndExprParser;
    TDCollectionParser *bitwiseAndExprParser;
    TDCollectionParser *ampEqualityExprParser;
    TDCollectionParser *equalityExprParser;
    TDCollectionParser *equalityOpRelationalExprParser;
    TDCollectionParser *relationalExprParser;
    TDCollectionParser *relationalOpShiftExprParser;
    TDCollectionParser *shiftExprParser;
    TDCollectionParser *shiftOpAdditiveExprParser;
    TDCollectionParser *additiveExprParser;
    TDCollectionParser *plusOrMinusExprParser;
    TDCollectionParser *plusExprParser;
    TDCollectionParser *minusExprParser;
    TDCollectionParser *multiplicativeExprParser;
    TDCollectionParser *multiplicativeOpUnaryExprParser;
    TDCollectionParser *unaryExprParser;
    TDCollectionParser *unaryExpr1Parser;
    TDCollectionParser *unaryExpr2Parser;
    TDCollectionParser *unaryExpr3Parser;
    TDCollectionParser *unaryExpr4Parser;
    TDCollectionParser *unaryExpr5Parser;
    TDCollectionParser *unaryExpr6Parser;
    TDCollectionParser *constructorCallParser;
    TDCollectionParser *parenArgListOptParenParser;
    TDCollectionParser *memberExprParser;
    TDCollectionParser *memberExprExtParser;
    TDCollectionParser *dotMemberExprParser;
    TDCollectionParser *bracketMemberExprParser;
    TDCollectionParser *argListOptParser;
    TDCollectionParser *argListParser;
    TDCollectionParser *primaryExprParser;
    TDCollectionParser *parenExprParenParser;

    TDCollectionParser *funcLiteralParser;
    TDCollectionParser *arrayLiteralParser;
    TDCollectionParser *objectLiteralParser;

    PKParser *identifierParser;    
    PKParser *stringParser;
    PKParser *numberParser;
        
    // keywords
    PKParser *ifParser;
    PKParser *elseParser;
    PKParser *whileParser;
    PKParser *forParser;
    PKParser *inParser;
    PKParser *breakParser;
    PKParser *continueParser;
    PKParser *withParser;
    PKParser *returnParser;
    PKParser *varParser;
    PKParser *deleteParser;
    PKParser *newParser;
    PKParser *thisParser;
    PKParser *falseParser;
    PKParser *trueParser;
    PKParser *nullParser;
    PKParser *undefinedParser;
    PKParser *voidParser;
    PKParser *typeofParser;
    PKParser *instanceofParser;
    PKParser *functionParser;

    // multi-char symbols
    PKParser *orParser;
    PKParser *andParser;
    PKParser *neParser;
    PKParser *isNotParser;
    PKParser *eqParser;
    PKParser *isParser;
    PKParser *leParser;
    PKParser *geParser;
    PKParser *plusPlusParser;
    PKParser *minusMinusParser;
    PKParser *plusEqParser;
    PKParser *minusEqParser;
    PKParser *timesEqParser;
    PKParser *divEqParser;
    PKParser *modEqParser;
    PKParser *shiftLeftParser;
    PKParser *shiftRightParser;
    PKParser *shiftRightExtParser;
    PKParser *shiftLeftEqParser;
    PKParser *shiftRightEqParser;
    PKParser *shiftRightExtEqParser;
    PKParser *andEqParser;
    PKParser *xorEqParser;
    PKParser *orEqParser;
    
    // single char symbols
    PKParser *openCurlyParser;
    PKParser *closeCurlyParser;
    PKParser *openParenParser;
    PKParser *closeParenParser;
    PKParser *openBracketParser;
    PKParser *closeBracketParser;
    PKParser *commaParser;
    PKParser *dotParser;
    PKParser *semiOptParser;
    PKParser *semiParser;
    PKParser *colonParser;
    PKParser *equalsParser;
    PKParser *notParser;
    PKParser *ltParser;
    PKParser *gtParser;
    PKParser *ampParser;
    PKParser *pipeParser;
    PKParser *caretParser;
    PKParser *tildeParser;
    PKParser *questionParser;
    PKParser *plusParser;
    PKParser *minusParser;
    PKParser *timesParser;
    PKParser *divParser;
    PKParser *modParser;
}
@property (nonatomic, retain) TDCollectionParser *assignmentOpParser;
@property (nonatomic, retain) TDCollectionParser *relationalOpParser;
@property (nonatomic, retain) TDCollectionParser *equalityOpParser;
@property (nonatomic, retain) TDCollectionParser *shiftOpParser;
@property (nonatomic, retain) TDCollectionParser *incrementOpParser;
@property (nonatomic, retain) TDCollectionParser *unaryOpParser;
@property (nonatomic, retain) TDCollectionParser *multiplicativeOpParser;

@property (nonatomic, retain) TDCollectionParser *programParser;
@property (nonatomic, retain) TDCollectionParser *elementParser;
@property (nonatomic, retain) TDCollectionParser *funcParser;
@property (nonatomic, retain) TDCollectionParser *paramListOptParser;
@property (nonatomic, retain) TDCollectionParser *paramListParser;
@property (nonatomic, retain) TDCollectionParser *commaIdentifierParser;
@property (nonatomic, retain) TDCollectionParser *compoundStmtParser;
@property (nonatomic, retain) TDCollectionParser *stmtsParser;
@property (nonatomic, retain) TDCollectionParser *stmtParser;
@property (nonatomic, retain) TDCollectionParser *ifStmtParser;
@property (nonatomic, retain) TDCollectionParser *ifElseStmtParser;
@property (nonatomic, retain) TDCollectionParser *whileStmtParser;
@property (nonatomic, retain) TDCollectionParser *forParenStmtParser;
@property (nonatomic, retain) TDCollectionParser *forBeginStmtParser;
@property (nonatomic, retain) TDCollectionParser *forInStmtParser;
@property (nonatomic, retain) TDCollectionParser *breakStmtParser;
@property (nonatomic, retain) TDCollectionParser *continueStmtParser;
@property (nonatomic, retain) TDCollectionParser *withStmtParser;
@property (nonatomic, retain) TDCollectionParser *returnStmtParser;
@property (nonatomic, retain) TDCollectionParser *variablesOrExprStmtParser;
@property (nonatomic, retain) TDCollectionParser *conditionParser;
@property (nonatomic, retain) TDCollectionParser *forParenParser;
@property (nonatomic, retain) TDCollectionParser *forBeginParser;
@property (nonatomic, retain) TDCollectionParser *variablesOrExprParser;
@property (nonatomic, retain) TDCollectionParser *varVariablesParser;
@property (nonatomic, retain) TDCollectionParser *variablesParser;
@property (nonatomic, retain) TDCollectionParser *commaVariableParser;
@property (nonatomic, retain) TDCollectionParser *variableParser;
@property (nonatomic, retain) TDCollectionParser *assignmentParser;
@property (nonatomic, retain) TDCollectionParser *exprOptParser;
@property (nonatomic, retain) TDCollectionParser *exprParser;
@property (nonatomic, retain) TDCollectionParser *commaAssignmentExprParser;
@property (nonatomic, retain) TDCollectionParser *assignmentExprParser;
@property (nonatomic, retain) TDCollectionParser *assignmentOpConditionalExprParser;
@property (nonatomic, retain) TDCollectionParser *conditionalExprParser;
@property (nonatomic, retain) TDCollectionParser *ternaryExprParser;
@property (nonatomic, retain) TDCollectionParser *orExprParser;
@property (nonatomic, retain) TDCollectionParser *orAndExprParser;
@property (nonatomic, retain) TDCollectionParser *andExprParser;
@property (nonatomic, retain) TDCollectionParser *andBitwiseOrExprParser;
@property (nonatomic, retain) TDCollectionParser *bitwiseOrExprParser;
@property (nonatomic, retain) TDCollectionParser *pipeBitwiseXorExprParser;
@property (nonatomic, retain) TDCollectionParser *bitwiseXorExprParser;
@property (nonatomic, retain) TDCollectionParser *caretBitwiseAndExprParser;
@property (nonatomic, retain) TDCollectionParser *bitwiseAndExprParser;
@property (nonatomic, retain) TDCollectionParser *ampEqualityExprParser;
@property (nonatomic, retain) TDCollectionParser *equalityExprParser;
@property (nonatomic, retain) TDCollectionParser *equalityOpRelationalExprParser;
@property (nonatomic, retain) TDCollectionParser *relationalExprParser;
@property (nonatomic, retain) TDCollectionParser *relationalOpShiftExprParser;
@property (nonatomic, retain) TDCollectionParser *shiftExprParser;
@property (nonatomic, retain) TDCollectionParser *shiftOpAdditiveExprParser;
@property (nonatomic, retain) TDCollectionParser *additiveExprParser;
@property (nonatomic, retain) TDCollectionParser *plusOrMinusExprParser;
@property (nonatomic, retain) TDCollectionParser *plusExprParser;
@property (nonatomic, retain) TDCollectionParser *minusExprParser;
@property (nonatomic, retain) TDCollectionParser *multiplicativeExprParser;
@property (nonatomic, retain) TDCollectionParser *multiplicativeOpUnaryExprParser;
@property (nonatomic, retain) TDCollectionParser *unaryExprParser;
@property (nonatomic, retain) TDCollectionParser *unaryExpr1Parser;
@property (nonatomic, retain) TDCollectionParser *unaryExpr2Parser;
@property (nonatomic, retain) TDCollectionParser *unaryExpr3Parser;
@property (nonatomic, retain) TDCollectionParser *unaryExpr4Parser;
@property (nonatomic, retain) TDCollectionParser *unaryExpr5Parser;
@property (nonatomic, retain) TDCollectionParser *unaryExpr6Parser;
@property (nonatomic, retain) TDCollectionParser *constructorCallParser;
@property (nonatomic, retain) TDCollectionParser *parenArgListOptParenParser;
@property (nonatomic, retain) TDCollectionParser *memberExprParser;
@property (nonatomic, retain) TDCollectionParser *memberExprExtParser;
@property (nonatomic, retain) TDCollectionParser *dotMemberExprParser;
@property (nonatomic, retain) TDCollectionParser *bracketMemberExprParser;
@property (nonatomic, retain) TDCollectionParser *argListOptParser;
@property (nonatomic, retain) TDCollectionParser *argListParser;
@property (nonatomic, retain) TDCollectionParser *primaryExprParser;
@property (nonatomic, retain) TDCollectionParser *parenExprParenParser;

@property (nonatomic, retain) TDCollectionParser *funcLiteralParser;
@property (nonatomic, retain) TDCollectionParser *arrayLiteralParser;
@property (nonatomic, retain) TDCollectionParser *objectLiteralParser;

@property (nonatomic, retain) PKParser *identifierParser;
@property (nonatomic, retain) PKParser *stringParser;
@property (nonatomic, retain) PKParser *numberParser;

@property (nonatomic, retain) PKParser *ifParser;
@property (nonatomic, retain) PKParser *elseParser;
@property (nonatomic, retain) PKParser *whileParser;
@property (nonatomic, retain) PKParser *forParser;
@property (nonatomic, retain) PKParser *inParser;
@property (nonatomic, retain) PKParser *breakParser;
@property (nonatomic, retain) PKParser *continueParser;
@property (nonatomic, retain) PKParser *withParser;
@property (nonatomic, retain) PKParser *returnParser;
@property (nonatomic, retain) PKParser *varParser;
@property (nonatomic, retain) PKParser *deleteParser;
@property (nonatomic, retain) PKParser *newParser;
@property (nonatomic, retain) PKParser *thisParser;
@property (nonatomic, retain) PKParser *falseParser;
@property (nonatomic, retain) PKParser *trueParser;
@property (nonatomic, retain) PKParser *nullParser;
@property (nonatomic, retain) PKParser *undefinedParser;
@property (nonatomic, retain) PKParser *voidParser;
@property (nonatomic, retain) PKParser *typeofParser;
@property (nonatomic, retain) PKParser *instanceofParser;
@property (nonatomic, retain) PKParser *functionParser;

@property (nonatomic, retain) PKParser *orParser;
@property (nonatomic, retain) PKParser *andParser;
@property (nonatomic, retain) PKParser *neParser;
@property (nonatomic, retain) PKParser *isNotParser;
@property (nonatomic, retain) PKParser *eqParser;
@property (nonatomic, retain) PKParser *isParser;
@property (nonatomic, retain) PKParser *leParser;
@property (nonatomic, retain) PKParser *geParser;
@property (nonatomic, retain) PKParser *plusPlusParser;
@property (nonatomic, retain) PKParser *minusMinusParser;
@property (nonatomic, retain) PKParser *plusEqParser;
@property (nonatomic, retain) PKParser *minusEqParser;
@property (nonatomic, retain) PKParser *timesEqParser;
@property (nonatomic, retain) PKParser *divEqParser;
@property (nonatomic, retain) PKParser *modEqParser;
@property (nonatomic, retain) PKParser *shiftLeftParser;
@property (nonatomic, retain) PKParser *shiftRightParser;
@property (nonatomic, retain) PKParser *shiftRightExtParser;
@property (nonatomic, retain) PKParser *shiftLeftEqParser;
@property (nonatomic, retain) PKParser *shiftRightEqParser;
@property (nonatomic, retain) PKParser *shiftRightExtEqParser;
@property (nonatomic, retain) PKParser *andEqParser;
@property (nonatomic, retain) PKParser *xorEqParser;
@property (nonatomic, retain) PKParser *orEqParser;

@property (nonatomic, retain) PKParser *openCurlyParser;
@property (nonatomic, retain) PKParser *closeCurlyParser;
@property (nonatomic, retain) PKParser *openParenParser;
@property (nonatomic, retain) PKParser *closeParenParser;
@property (nonatomic, retain) PKParser *openBracketParser;
@property (nonatomic, retain) PKParser *closeBracketParser;
@property (nonatomic, retain) PKParser *commaParser;
@property (nonatomic, retain) PKParser *dotParser;
@property (nonatomic, retain) PKParser *semiOptParser;
@property (nonatomic, retain) PKParser *semiParser;
@property (nonatomic, retain) PKParser *colonParser;
@property (nonatomic, retain) PKParser *equalsParser;
@property (nonatomic, retain) PKParser *notParser;
@property (nonatomic, retain) PKParser *ltParser;
@property (nonatomic, retain) PKParser *gtParser;
@property (nonatomic, retain) PKParser *ampParser;
@property (nonatomic, retain) PKParser *pipeParser;
@property (nonatomic, retain) PKParser *caretParser;
@property (nonatomic, retain) PKParser *tildeParser;
@property (nonatomic, retain) PKParser *questionParser;
@property (nonatomic, retain) PKParser *plusParser;
@property (nonatomic, retain) PKParser *minusParser;
@property (nonatomic, retain) PKParser *timesParser;
@property (nonatomic, retain) PKParser *divParser;
@property (nonatomic, retain) PKParser *modParser;
@end
